### ISSUE TITLE
Request REST method with parameters and server-end always responds status 405

### ISSUE THREAD

**Issue by FuweiChin** [gk-brown/HTTP-RPC#84]
**Steps to Reproduce**:
1. given a method like  
	```
	@RequestMethod("GET")
	@ResourcePath("/sum")
	public double getSum(double a, double b) {
		return a + b;
	}
	```
2. make a request: `GET /math/sum?a=1&b=2`

**Expected Result**:
DispatcherServlet behaves as article [HTTP-RPC introdution](https://dzone.com/articles/a-lightweight-alternative-to-jax-rs) says.

**Actual Result**:
`405 method not allowed`

By debugging, I found that  method parameter names cannot be correctly decompiled.  
> java.lang.relect.Method#getParameters() returns results like double arg0 double arg1, which WILL NOT match request parameter names in 'a=1&b=2'

Additional Information:  
+ Java: jdk1.8.0_92 on Windows
+ ServletContainer: Tomcat 8.5 managed by Eclipse 4.7

It is clear that the issue is caused by some limitations of Java Reflection.

Maybe we can avoid using Java Relection by adding `@SearchParam` support for method parameters, to connect request parameters and method parameters.

**Comment by gk-brown** [comment]
Make sure you are passing the -parameters flag to the compiler; for example:

<compilerarg value="-parameters"/>

**Comment by gk-brown** [comment]
Make sure you are passing the `-parameters` flag to the compiler; for example:

    <compilerarg value="-parameters"/>

Otherwise, method parameter names will not be available at runtime. See the "war" target in the server build script for more information:

https://github.com/gk-brown/HTTP-RPC/blob/master/Server/Java/httprpc-server/build.xml

**Comment by FuweiChin** [comment]
It does work by adding compiler arg "-parameters",   
```
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-compiler-plugin</artifactId>
	<version>3.5.1</version>
	<configuration>
		<source>1.8</source>
		<target>1.8</target>
		<compilerArgs>
			<compilerArg>-parameters</compilerArg>
		</compilerArgs>
	</configuration>
</plugin>
```
but only works when I compile project with through `mvn compile` or other maven goals which triggers maven compile.

That means I have to run maven build maven each time I changed java source, or I have to configure Eclipse to compile java source with compiler arg '-parameters' too.

**Comment by gk-brown** [comment]
Correct. Maybe a future JDK update will enable this argument by default.

**Comment by gk-brown** [comment]
Closing issue since `-parameters` flag is a JDK feature (not specific to HTTP-RPC).
