### ISSUE TITLE
org.httprpc.sql.Parameters parsing problems when date patterns are present in sql

### ISSUE THREAD

**Issue by arisjramos** [gk-brown/HTTP-RPC#90]
When having date patterns in sql it makes org.httprpc.sql.Parameters to fail.

(bad example i know...)
select * from my_table where my_criteria = :myVar1 and my_collumn_of_type_date between  to_date("2019-01-01 00:00:00","YYYY-MM-dd HH24:mi:ss") and sysdate.

org.httprpc.sql.Parameters will think thad de pattern containg ":" char are variables to take account and will reques will fail with an error of type "Invalid index column"

**Comment by gk-brown** [comment]
Based on a quick Google search, some JPA implementations appear to have a similar issue.

However, in general you shouldn't be hard-coding date values in your SQL anyway. That's what parameters are for.  🙂

**Comment by gk-brown** [comment]
On the other hand, it should be possible to include a format string in a query, as you have done in your example. `Parameters` could potentially be updated to ignore colons that are enclosed in quotes.

**Comment by gk-brown** [comment]
This is fixed. The `Parameters` class now ignores colons within single quotes.

**Comment by vivekanandg** [comment]
What if I have to cast something?

eg: SELECT '2019-01-01'::date

**Comment by gk-brown** [comment]
I think my earlier comment may apply in this case. Under what circumstances would you want to hard-code a string value like that instead of providing it as a parameter value?

**Comment by vivekanandg** [comment]
What if I want to do the below or something similar

:someTimestamp::date

**Comment by gk-brown** [comment]
Use CAST()?

**Comment by vivekanandg** [comment]
Fair.

However, I'm using this in a platform appreciate and cannot force end users
to follow this convention.

I'll quickly try and patch this.

**Comment by vivekanandg** [comment]
* platform application

**Comment by gk-brown** [comment]
It seems like the :: operator is specific to Postgres. However, I could see an argument for ignoring two consecutive colon characters. This shouldn't be too hard to implement.
