### ISSUE TITLE
No parameter is detect after multi line comment

### ISSUE THREAD

**Issue by rjbgaspar** [gk-brown/HTTP-RPC#93]
Hi,

    @Test
    public void testParameters1() {
        // Setup
        final String namedParameter = "parameter";
        final String query =
                "SELECT TOP 1 * "
                        + "FROM GV.SINVOICED "
                        + "/* Comment */ "
                        + "WHERE NUM_0 = :" + namedParameter;

        final HashMap<String, Object> arguments = new HashMap<>();
        arguments.put(namedParameter, "FCL-V119/00001");

        Parameters parameters = Parameters.parse(query);
        logger.info(parameters.getSQL());
    }

    @Test
    public void testParameters2() {
        // Setup
        final String namedParameter = "parameter";
        final String query =
                "SELECT TOP 1 * "
                        + "FROM GV.SINVOICED "
                        + "WHERE NUM_0 = :" + namedParameter;

        final HashMap<String, Object> arguments = new HashMap<>();
        arguments.put(namedParameter, "FCL-V119/00001");

        Parameters parameters = Parameters.parse(query);
        logger.info(parameters.getSQL());
    }

testParameters1
16:30:53.244 [main] INFO com.gv.webapp.businessanalytics.services.HttpRpcSqlTest - SELECT TOP 1 * FROM GV.SINVOICED /* Comment */ WHERE NUM_0 = :parameter

16:30:53.250 [main] INFO com.gv.webapp.businessanalytics.services.HttpRpcSqlTest - SELECT TOP 1 * FROM GV.SINVOICED WHERE NUM_0 = ?

In the first test case the parameter is not replaced by "?"

Thank you in advance
RG

**Comment by gk-brown** [comment]
This is resolved.

**Comment by rjbgaspar** [comment]
Hi,
Check it is ok.

Thank you.
