### ISSUE TITLE
How to build and deploy?

### ISSUE THREAD

**Issue by abeq** [gk-brown/HTTP-RPC#94]
Probably I think httprpc-test is servlet that work with Tomcat, etc.
Please let me know how to build and deploy, because I want to try it.
Thank you.

**Comment by gk-brown** [comment]
`./gradlew assemble` in the project root directory will generate the WAR file:

_httprpc-test/build/libs/httprpc-test-1.0.war_

You can then either copy this to your Tomcat _webapps_ directory or create a symbolic link to it.

There is a test form available at:

http://localhost:8080/httprpc-test-1.0/index.jsp

Most of the examples should work fine, but the MongoDB and MySQL examples require some additional setup.

You can also use either of the mobile apps here for testing (assuming that the test webapp is accessible at the above URL):

https://github.com/gk-brown/Kilo

**Comment by gk-brown** [comment]
I’m assuming this is resolved. Please re-open if not.

**Comment by abeq** [comment]
Hi, thank you for your kindly instruction and advise.
I apologize for the delay in thanking you.

About with MySQL sample, there is only method for GET.
Does POST, PUT, DELETE also work correctly?
Is there sample for it?

Thank you and best regards,

**Comment by gk-brown** [comment]
There is no MySQL sample for the other operations, but they are supported. You can see some additional examples here: 

https://github.com/gk-brown/HTTP-RPC/tree/master/httprpc-test/src/main/java/org/httprpc/test
